### ISSUE TITLE
No Text on Server

### ISSUE THREAD

**Issue by WenXin20** [Lynzl/Minecraft-TextDamageIndicators#1] opened 2020-09-25 22:52 UTC
`Minecraft v1.15.2`
`Forge v31.2.36`
`Text Damage Indicators v1.0.0`

The text for damage taken doesn't display on a server, even though there are no errors printed in the log.

**Comment by Lynzl** [comment] 2020-09-25 23:19
Hello!
Thanks for the report again!

I'll look into it.

Is the issue only on players or monsters too?

**Comment by WenXin20** [comment] 2020-09-25 23:44
I'm not sure about players since I'm the only one one my server at the moment. But it's not working for any mobs.

**Comment by Mali321** [comment] 2020-10-01 22:35
I'm having the same issue on a 1.16.3 server. I've got a handful of other mods, all client side. There are no server side mods running.
MC: 1.16.3
Forge: 34.11
TDI: 2.0.0

**Comment by Lynzl** [comment] 2020-10-05 20:53
Duplicate of #3

**Closed** 2020-10-05 21:53 UTC

**Comment by WenXin20** [comment] 2020-10-06 16:43
Will the fix be released for 1.15.2 as well?

**Comment by Lynzl** [comment] 2020-10-06 16:47
Yes.
